# Generated by Django 5.0.7 on 2024-07-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0004_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
