# Generated by Django 5.0.7 on 2024-08-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0006_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
