# Generated by Django 5.0.7 on 2024-08-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0007_course_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
